### ISSUE TITLE
Bug - fail to export / build

### ISSUE THREAD

**Issue by ed-thomas** [jyapayne/Web2Executable#100]
Hi, I am not able to get this to compile the files (v0.3.1b in W10, trying to build for linux64, windows32 and Mac64).  Download of nw.js binaries is ok. Then, a few seconds after clicking on Export, the following error window appears and the build fails.  Is this something I am doing wrong or is this a bug?

![web2exe v0 3 1b error](https://cloud.githubusercontent.com/assets/2897225/11290343/9275d3da-8efb-11e5-84f1-806ee216be32.png)

Thanks.

**Comment by jyapayne** [comment]
Hmmm, it may be a permissions issue. Do you have write permissions to the AppData folder? (C:\Users\<YourUser>\AppData\Local\Web2Executable\Web2Executable\files)

**Comment by ed-thomas** [comment]
I tried running as administrator but that made no difference. Is there anything else I could try to help identify the cause?
On 19 Nov 2015 11:38 p.m., Joey <notifications@github.com> wrote:Hmmm, it may be a permissions issue. Do you have write permissions to the AppData folder? (C:\Users<YourUser>\AppData\Local\Web2Executable\Web2Executable\files)

**Comment by 2braincells2go** [comment]
On one of my Win 10 machines (use 3 and only one required change???) had to use:

C:\Users\Public\Public Documents\Web2Executable\files

Would not save to default.

Like I said, only one of three machines had this issue. Strange. Was told because I did fresh install of Win 10 on that particular machine was reason. How true that is, no clue:)

**Comment by jyapayne** [comment]
Woody, I can't say for sure or not whether it was because you had a fresh install of Windows 10. I freshly installed Windows 10 on a new box about a week ago, and tried running Web2Exe with a web project that I have on it. I used @ed-thomas's export configuration and it seemed to run fine.

@ed-thomas, do you have any special hard drive configurations? For example, do you have any network hard drives, or are you running Web2Exe with files that are on separate hard drives?

**Comment by jyapayne** [comment]
@ed-thomas, can you try [this version](http://www.mediafire.com/download/7hj58c1kibrkhic/Web2ExeWin-v0.3.2b.zip)?

**Comment by ed-thomas** [comment]
I found I encountered a similar permissions problem with v0.3.2b, so I changed the export directory to on inside the Public folder and it works perfectly!  What an excellent program!
Having seen the output, I have one question: is there a way to compile the files together into a single file .exe?  I had "single instance" checked, but that seemed to make no difference.
Thank you!
Ed
Date: Fri, 20 Nov 2015 09:02:29 -0800

**Comment by jyapayne** [comment]
@ed-thomas Glad to see you solved it :)

The files that you see in the output are simply the ones that come in the NW.js distribution. There are some dll files that you will need based on your application. For example, if you need audio support, you'll have to keep ffmpegsumo.dll. But if you don't need audio, you can delete it. The **required** files for a minumum application are: YourApp.exe, nw.pak, and icudtl.dat. All others can be deleted from the export folder and your app will still work.

As for combining those 3 files, you'll have to use a separate tool. Single instance just ensures that a user can't open two windows of your application at one time.

**Comment by ed-thomas** [comment]
That's great - thank you for your help!
On 20 Nov 2015 1:54 p.m., Joey <notifications@github.com> wrote:@ed-thomas Glad to see you solved it :)

The files that you see in the output are simply the ones that come in the NW.js distribution. There are some dll files that you will need based on your application. For example, if you need audio support, you'll have to keep ffmpegsumo.dll. But if you don't need audio, you can delete it. The required files for a minumum application are: YourApp.exe, nw.pak, and icudtl.dat. All others can be deleted from the export folder and your app will still work.

As for combining those 3 files, you'll have to use a separate tool. Single instance just ensures that a user can't open two windows of your application at one time.

**Comment by 2braincells2go** [comment]
Hey Joey.

Just re-read what I typed - bass ackwards:)

What I meant to say was: have three win 10 machines. The one with export issues I did NOT do a fresh install on. it was an "upgrade from win 7". Other two that did not have issues were fresh installs.

Sorry for confusion, had kids pulling me in 6 directions that day.

Had issues with many software that used/accessed the user folders. Something to do with write/owner permissions after going the upgrade path. Since I started using win 10 way back, asked in the win 10 developer forum and they suggested using the C:\Users\Public\Public Documents\

Just wanted to clear up in case others may have issues.

Cheers!
