### ISSUE TITLE
Host executables on github

### ISSUE THREAD

**Issue by antonellopasella** [jyapayne/Web2Executable#101]
I thisnk it would be more reliable, dont'you?

**Comment by jyapayne** [comment]
Are you having issues downloading from Mediafire?

**Comment by antonellopasella** [comment]
A virus alert by Chrome 😒

Il venerdì 20 novembre 2015, Joey <notifications@github.com> ha scritto:

> Are you having issues downloading from Mediafire?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jyapayne/Web2Executable/issues/101#issuecomment-158458190>
> .
>


-- 
Antonello Pasella http://www.pasella.it

**Comment by jyapayne** [comment]
Ah, I see. Unfortunately, hosting the files on github is not an option because it would obfuscate the object files and create pretty slow cloning. If you have any other suggestions besides mediafire and github, I'd be happy to switch to something that works for you. The only reason I use mediafire right now is because it's separate from my other accounts and it has 15 GB of free data.

**Comment by cmawhorter** [comment]
Maybe https://github.com/blog/1547-release-your-software ?

> Today, we're excited to announce Releases, a workflow for shipping software to end users. Releases are first-class objects with changelogs and binary assets that present a full project history beyond Git artifacts. They're accessible from a repository's homepage:

I think only required change is to start tagging releases and uploading there instead.

**Comment by jyapayne** [comment]
:) That's a good idea. Even though I download software on github using this mechanism a lot, I haven't thought of using it for Web2Exe releases. I think I'll switch over :)
