### ISSUE TITLE
Possible hardcoded paths

### ISSUE THREAD

**Issue by ironikart** [jyapayne/Web2Executable#105]
When using the 0.3.3b release (GUI) on OSX v10.11.1 and trying to export for OSX 64bit I get the following message:

```
['Traceback (most recent call last):\n', '  File "/Users/joey/Projects/Web2Executable/command_line.py", line 760, in make_output_dirs\n', '  File "/Users/joey/Projects/Web2Executable/command_line.py", line 638, in create_icns_for_app\n', '  File "/Users/joey/Projects/Web2Executable/pycns.py", line 19, in save_icns\n', '  File "/Users/joey/Projects/Web2Executable/pycns.py", line 14, in encode_image_to_icns\n', '  File "/Users/joey/Projects/Web2Executable/icns_info.py", line 994, in parse_image\n', '  File "/Users/joey/Projects/Web2Executable/png.py", line 1958, in read_flat\n', '  File "/Users/joey/Projects/Web2Executable/png.py", line 1920, in read\n', '  File "/Users/joey/Projects/Web2Executable/png.py", line 1719, in preamble\n', '  File "/Users/joey/Projects/Web2Executable/png.py", line 1706, in validate_signature\n', 'FormatError: FormatError: PNG file has invalid signature.\n']
```

No idea where `/Users/joey` is coming from (quick text search only revealed some commented text in the bash script)

**Comment by jyapayne** [comment]
There aren't any hard coded paths. The packet I use keeps my local paths so that it's easy to debug. 
I am aware of this issue. It's caused when a .icns file has a jpeg encoded inner icon format. Basically, you'll need to encode your .icns file differently, or use a png file for the Mac Icon (it will be converted to an icns file)

**Comment by 2braincells2go** [comment]
Hey Joey.

Having a very similar issue but Using Win and Web2Exe v0.3.2b. Tried v0.3.1b with same results.

![2015-12-18_084223](https://cloud.githubusercontent.com/assets/2567500/11899288/8d57b3b8-a563-11e5-9f66-37e233163e12.png)

What the heck am I doing wrong?

Thanks man!

**Comment by jyapayne** [comment]
@2braincells2go It looks like you're hitting the Windows 255 character limit with your long node modules path. You might be able to fix the issue by running this npm module: https://docs.npmjs.com/cli/dedupe

**Comment by 2braincells2go** [comment]
Ok, thanks Joey.

Not positive know how to solve. Install this module and it handles things in future?

but if it were you:

Where would you place projects so this will not happen in first place?

**Comment by jyapayne** [comment]
I don't think you have to install it. It might be included when you install the more recent versions of npm. Basically, in the root of your project, where your node_modules folder is located, you'll have to open up a command line window and enter `npm dedupe` and it will move some of your dependencies around so that they aren't so deeply nested.

This is a [well known issue with npm](https://github.com/npm/npm/issues/3697) and there's not really anything you can do to prevent it except know that it's going to happen at some point and then run this module or a similar one to make the paths shorter. It's an annoying problem for sure since it's only related to Windows and the APIs that Python uses in Windows.

**Comment by 2braincells2go** [comment]
Wonderful advice Joey, thank you.

I have never ran into it before but then again this is "amateur hour":) I should have started learning all this when I was a much younger man. Like a 1st Sargent told a 2nd lieutenant long ago when I was in military: if you had one more braincell, they would fight and kill each other!

Thanks again Joey.

**Comment by jyapayne** [comment]
:D I didn't know you were in the military. What was your rank?

You're very welcome, Woody. Hope your classes are coming along well :)

**Comment by 2braincells2go** [comment]
I got out in 1985 as a lowly staff sergeant. Loved my time in and learned a lot but way too many rules for this ole boy:) Don;t get me wrong, excellent training and wonderful experience just not for head strong people, lol.

I teach classes for teens who have issues with authority, so I fit into that well. Basically show them how to use a computer and do something creative with their time. So classes are going great!

**Comment by jyapayne** [comment]
:) I think there would be too many rules for me as well.

That's cool :) Glad to hear that they're going well!
