### ISSUE TITLE
OSX - W2E 0.4.0b crashes on start

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#117]
Double click on W2E and it appears in dock for short moment then drops out. Error log appears clean but system log gives -
22:01:23 com.apple.launchd.peruser.501:  (Web2Executable.715120[420]) Exited with code: 255
W2E 0.3.4b was OK.
OSX 10.9.5 Mavericks 64bit

**Comment by jyapayne** [comment]
Hmm, seems like it might be the switch to Python 3. There isn't any difference feature wise that I added in 0.4.0b besides handling unicode better (because of Python 3). For now you should just use 0.3.4b since it's equivalent. Thanks for letting me know about this issue. I'll see if I can figure out what's wrong when I've got some time.

**Comment by jyapayne** [comment]
@Blatman I couldn't seem to reproduce this error. I tried a fresh install of El Capitan on Parallels (I couldn't find a 10.9.5 image) and Web2Exe started up fine. It sounds like the process just crashes before it gets to any Python code, or else there would be something in the logs. If you know where I could get an image of 10.9.5, that would be helpful in debugging :)

**Comment by Blatman** [comment]
Thanks Joey, I just tried W2E on Yosemite as well and it starts OK and I think Yosemite has Python 3 bundled whereas Mavericks does not (it has 2.7). I guess if W2E needs to have Python 3 installed then I'll have to stick with 0.3.4b for the while on Mavericks - haven't really got the time to try installing Python 3.
Not sure where to get a 10.9 image, mine came with the machine.

Cheers.

**Comment by jyapayne** [comment]
There isn't a requirement to have any Python installed, since it's bundled with Web2Exe. The only issue may be incompatible libraries that Python 3 uses that are either outdated or not present on Mavericks. When I make any other changes to the functionality of Web2Exe, I'll be sure to include a Python 2.7 build for you and any others on 10.9 :)
