### ISSUE TITLE
Invalid version string: 'off'

### ISSUE THREAD

**Issue by banezaklan** [jyapayne/Web2Executable#125]
Hi, trying command line version v0.4.4b on El Capitan 10.11.4 OS X, and getting following error:

```
 Web2ExeMac-CMD ./web2exe-mac
Updating nw versions...Failed to execute script command_line
Traceback (most recent call last):
  File "command_line.py", line 1457, in <module>
  File "command_line.py", line 1319, in main
  File "command_line.py", line 263, in init
  File "command_line.py", line 268, in update_nw_versions
  File "command_line.py", line 376, in get_versions
  File "semantic_version/base.py", line 75, in __init__
  File "semantic_version/base.py", line 192, in parse
ValueError: Invalid version string: 'off'
```

Any ideas?

**Comment by wJsJwr** [comment]
Because the script uses a very simple regex `(\S+) / \S+`  to fetch versions from nwjs' CHANGELOG. Unfortunately , there is a line:

> - Fix: Unable to turn off / disable debug.log (#4637)

in the newest changelog and it matches the regex too. Then the script get a version string "off", which is not a correct version string.

I've issued a PR #126 , waiting for  merging. 

Or you can simply go to line 371 in `command_line.py`, change `(\S+) / \S+` to `(\S+) / \d{2}-\d{2}-\d{4}` and fix the problem locally.

**Comment by jyapayne** [comment]
@wJsJwr Thank you for fixing the issue :) I'll pump out a new build today with the changes!

**Comment by jyapayne** [comment]
The new build is up and should fix this issue. Let me know if it's not working!
