### ISSUE TITLE
Feature - macappstore flavor build

### ISSUE THREAD

**Issue by Montoya** [jyapayne/Web2Executable#139]
I know there's only one version (12.3) that offers a macappstore flavor build, but would it be crazy to include a checkbox for exporting a Mac app with this build?

**Comment by jyapayne** [comment]
I'm not quite sure how to do this one, but I could look at https://github.com/johansatge/nwjs-macappstore-builder for guidance.

**Comment by Montoya** [comment]
I think this might be helpful too, it supports all the flavors including macappstore: https://github.com/evshiron/nwjs-builder

**Comment by jyapayne** [comment]
Hmm, I don't think I'll be able to support this right now. Unfortunately, since there are a lot of compatibility issue between 0.12.X and 0.13.X and higher, I have decided to drop support for 0.12.X. It looks like MAS support [is planned for the future for NW.js](https://github.com/nwjs/nw.js/issues/4556), but maybe it's better for you to use Electron instead since it comes with MAS builds since a while ago.
