### ISSUE TITLE
Minor > display LTS tag in versions

### ISSUE THREAD

**Issue by Inateno** [jyapayne/Web2Executable#143]
Hi,

As usual, very useful software thanks for your good work :) !

Here we would like to use only the LTS version of NW.JS.
Because our team is big and not up-to-date on each dependencies, it would be nice if the W2E soft could display which LTS version with a tag "LTS" (like beta/alpha/rc tags).

Of course this is a minor issue, but it would be nice and I think it's good for those who want to use this and convince companies. I don't know how to get this informations automatically, I only saw it on their blog http://nwjs.io/blog/.

But LTS will not change every days (only on minor version because it's 0.14.X).

Tell me what you think.
Bye

**Comment by jyapayne** [comment]
Hey :)

Although I don't disagree with the potential usefulness of this, the complexity it adds to the code and the time it would take doesn't seem worth it. The only place the LTS tag is available is on the NW.js blog, and would require quite a bit of code to parse (even then, the page structure could change). Plus, I think it's easy enough to find out which is the LTS release from the NW.js page since it doesn't change that often.

**Comment by Inateno** [comment]
Yeah agree with that but not everyone go look this information. Of course I was pretty sure the work required isn't worth it.
Well. I'm gonna make an intern documentation about this, way easier ;)
