### ISSUE TITLE
Enable naming resulting directories after a pattern

### ISSUE THREAD

**Issue by Forecaster** [jyapayne/Web2Executable#150]
Which could include things like the build datetime, application version and name from the package.json and nw version used.

Something like "%n v%v - nw %j" becomes "appname v1.0 - nw 0.12.3"

This is the main reason I wanted to be able to use it on my server, to easily be able to package the application files easily with the proper names.

**Comment by jyapayne** [comment]
This is a good idea :) I will look at it when I get the chance!

**Comment by jyapayne** [comment]
I've implemented  the first version of this. The way it works is a new field, Output Name Pattern, in the "Export Settings" tab. Instead of your suggestion of a few options, I decided to include the option to reference any setting by name (the field will auto-complete setting names).

For example, if you want to use the App Name setting in the App Settings tab, typing "App N" will auto-complete and if you select it from the drop-down, it will replace the text with an identifier (in this case, %(app_name)). You can also reference these identifiers in the auto-complete box by typing "%(" and viewing all of the options which are named by their [NW.js manifest format](http://docs.nwjs.io/en/latest/References/Manifest%20Format/).

**Comment by jyapayne** [comment]
There is no option yet to include the build date. I will update later if this is a strong requirement for you.
