### ISSUE TITLE
Parsing package-json: node-remote

### ISSUE THREAD

**Issue by CyberianIce** [jyapayne/Web2Executable#154]
As of version 0.13+, NWJS accepts array of strings for node-remote parameter, example (package.json):

`"node-remote": [ "http://remotehost", "https://remotehost" ]`

Unfortunately, I found Web2Executable strip this parameter back into multiple strings in intermediate package.json, which will cause newly created application fail to load with following code into (package.json):

`"node-remote": "https://localhost", "http://localhost", "https://remotehost", http://remotehost"`

Exception trown:

> Invalid value for 'app.urls[0]': Missing scheme separator

# To fix this, one need to edit settings.cfg:62
from:
`type='string'`
to:
`type='strings'`

**Pay additional attention that there should be no whitespaces after commas.**

Thanks for your commitment, keep up good work & have fun!

**Comment by jyapayne** [comment]
Thank you for mentioning this! This is happening due to backwards compatibility. I'm thinking of removing compatibility with NW.js < 0.13.X in order to simplify a lot of the code, and this is one of the issues. I currently have no way to have separate settings for particular versions of NW.js, which means I either have to build that functionality, or remove backwards compatibility.
