### ISSUE TITLE
How to hide toolbar

### ISSUE THREAD

**Issue by omidgharib** [jyapayne/Web2Executable#156]
I couldn't find a way to hide the chrome toolbar in my .exe app.
I don't have the "Show Toolbar" option.
how is it possible?
Thanks in advance

**Comment by jyapayne** [comment]
What version of nw.js and web2exe are you using?

**Comment by jyapayne** [comment]
For reference, the "Show Toolbar" option does not work in greater versions of NW.js. Toolbar is disabled since 0.13.0 by default. The only way to enable this is by downloading the "SDK" version. You can set that as a download option in the download settings. [Read here](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#manifest-format) for more information.
