### ISSUE TITLE
Web2Exe doesn't understand position: null

### ISSUE THREAD

**Issue by Forecaster** [jyapayne/Web2Executable#166]
I found that after building the application with Web2Executable and attempting to start it no window appears, but a number of processes start in the background. They keep running until killed.

I tried with and without compression and it was the same. But my application runs fine when started from the IDE, and I've noticed that Web2Exe changes the package.json by adding a ton of stuff.

So I tried building the application as an uncompressed folder, then I overwrote the package.json there with my original one, and then the application worked properly.

It would seem that Web2Exe is adding invalid options to the package.json or something. It'd be great if it wouldn't modify it if you didn't want it to.

Since I can't easily fix the package.json when using compression, and also would have to do it for each build, for each OS.

**Comment by jyapayne** [comment]
That's very interesting. It seems like since nwjs version 0.16.1 something has changed to make the package.json invalid. If you don't need specific features from the latest releases, try exporting with nwjs 0.16.1 for now while I look into it. 

There is no way, that I'm aware of, to manipulate NW.js without modifying the package.json. If you know of a way, that would be cool, but otherwise the package.json manipulation has to stay.

**Comment by Forecaster** [comment]
I've tried building with 16.1, which is my current dev-version because I'm lazy, and it still breaks. I've not tried versions prior to that but no builds I've made with 16.1 and up have worked.

Also I'm not sure what you mean by "manipulating NW.js". If you mean the settings in the gui of Web2Exe such as the name, window parameters etc I don't really need that. I configure my package.json properly manually. So unless you always need to modify it to build it I could do with an option to have it not touch it for users who'd rather write it themselves if possible.

(I don't touch anything in the App Settings or Window Settings tabs)

**Comment by jyapayne** [comment]
So you're looking for something like a "readonly" mode that doesn't modify the package.json at all? That means all you'd want to use Web2Exe for is building and not setting options?

**Comment by Forecaster** [comment]
Exactly

**Comment by Forecaster** [comment]
I figured out the problem.

Web2Exe sets window: position to "None", while valid values are null, "center" or "mouse".

I have it set to null in my own package.json, but it's being overwritten on build and set to "None" instead, as does leaving "position" out of the package.json.

**Comment by jyapayne** [comment]
That's very weird. Which version of Web2Exe are you using? Since a long time ago, I put a check in the code for that so if a value is not set or empty, no values are added to the package.json. You're certain you didn't have the window position set before opening Web2Exe? Also, are you using the GUI or the CMD version?

This is the way Web2Exe manages the package.json file:

1. Open a project
2. Load all values from the package.json and populate fields
3. When a field changes, write the value to the package.json. If the field changes to empty or none, remove the field from the package.json.
4. On export, write some Web2Exe specific project settings to the package.json, keeping any fields that were already there that weren't explicitly set by Web2Exe, and copy the package.json to the export folder.

As you can see, although Web2Exe modifies the package.json, it keeps any settings that aren't explicitly set by you and only changes NW.js fields when you change them. It shouldn't add any fields that you don't want, and if it does, that means there's a bug.

When trying to reproduce the window position is None, I could only do it if I manually set the window position to be None in the package.json **before** opening Web2Exe.

**Note:** If you change anything in the package.json while Web2Exe is open, it doesn't understand those changes, so it will blow away anything you do. If you want to modify the package.json, do it before Web2Exe is open and it will keep anything you set.

**Comment by Forecaster** [comment]
That doesn't reflect what I see at all. I'm using v0.5.3b of the GUI version. (From the file in Releases named "Web2ExeWin-v0.5.3b.zip")

Like I said, I have window position defined in my package.json with the value null (not "null").

And without touching any of the fields, just hitting "Build" a bunch of stuff is added to the package.json

I'm doing this right now:
1. Closing Web2Exe
2. Verifying that my package.json looks correct: https://gist.github.com/Forecaster/99329f5e03a1f1cf7aaf782652a8472e
3. Start Web2Exe & Load the project
4. Without clicking anything else, immediately click "Export" (It's already set to uncompressed folder)
5. In the output dir, the now built win64x version's package.json look like this: https://gist.github.com/Forecaster/9deac8a4662ebe404d4769073e83690d

**Comment by jyapayne** [comment]
Right. Web2Exe will put in the default options if nothing is set. I need to change that because you're right, there shouldn't be any modifications if you don't want them.

Ah, I see. That's the problem. You need to remove the position option entirely from your package.json as a workaround for now. It looks like if the position is null from the get go (same as leaving it out of the package.json), Web2Exe gets confused and changes it to "None". I can reproduce this now and I'll fix it so it doesn't happen again. I'll also try to ensure that no extra fields related to NW.js are added.

**Comment by Forecaster** [comment]
Why do you even write all those settings to it?

**Comment by Forecaster** [comment]
I'd really like a "don't touch it" option that leaves it as it was input if possible.

**Comment by jyapayne** [comment]
The reason for adding the Web2Exe options was to keep a central place for the settings to live. Truth be told, I could move those settings into a separate file, which I am planning to do because writing them in the package.json frustrates people (as you know :P). Since you brought this to my attention, I'll be working on a "don't touch it" option that leaves the package.json unmodified. I'll also make sure that options that are not touched will not be added to the package.json.

**Comment by Forecaster** [comment]
Sounds great! Thanks!

And I guess the reason why removing "position" didn't work before when I tried it was because I didn't know to restart Web2Exe after modifying the package.json

**Comment by jyapayne** [comment]
Position: null is now ignored in the latest code. I'll pump out a build after a few more issues are down.
