### ISSUE TITLE
Need nw@0.12< support

### ISSUE THREAD

**Issue by webkitten** [jyapayne/Web2Executable#181]
nw versions like 0.12.3 gone from select versions. I need only this version, because some features in nw 0.13> deprecated

**Comment by jyapayne** [comment]
Sorry, I don't support less than version 0.13.0. What features do you need from the old versions?

**Comment by webkitten** [comment]
problem solved by using nwjs-builder package.
i need support 
`"single-instance": false` 
and
`"toolbar": true`

**Comment by jyapayne** [comment]
In nwjs greater than 0.13.0, you can download an sdk build in the download settings to access the [debug tools](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/). But as for the single instance flag, if you need it, you need it.

Unfortunately, supporting those older versions of nwjs is too much work for me since they are quite different than the new versions.
