### ISSUE TITLE
OSX - All icons displayed in TBD bar if windows icon populated first

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#189]
OSX 10.11.6  El Capitan
using NWjs 0.20.3-osx

This is more a niggle and has been happening for quite a while.
If the windows icon is chosen first then all the icon types will be displayed but if the windows icon is the last to be done then each icon will be displayed according to the appropriate selection.
eg: mac icns then exe icon then windows icon - OK
Cheers

**Comment by jyapayne** [comment]
I'm not sure I understand the behavior you expect. Can you elaborate more?

Here's the logic that I wrote this under: If someone specifies the window icon first, then make that the default icon for the project if the other icons are blank (display it on any blank icon). The other two don't work this way because I would think it's more common to want a specific icon for Mac/Exe than a generic window icon for the whole project (Web2Exe converts the window icon to ICNS and Exe format if the other two are not specified)

**Comment by Blatman** [comment]
Ah - Ok Joey, looks like it is design intent so that's fine , I was just expecting only one icon for each selection so I'll close this one now.

Cheers.
