### ISSUE TITLE
Launching Application Loads NWJS Splash Screen

### ISSUE THREAD

**Issue by titansoftime** [jyapayne/Web2Executable#208]
This is probably something that I am doing wrong, sorry in advance.

It seems that my application is exporting correctly, the file is the expected size. Problem is when I launch it I just get the windowed njws splash screen.

My app works fine when exported via nw builder-phoenix except all the assets are exposed, ready to modify and exploit.

What am I doing wrong?

package.json:

```

{
    "app_name": "titansoftime",    
    "description": "Titans of Time",
    "main": "index.html",
    "name": "titansoftime",
    "version": "0.1",
    "webexe_settings": {
        "blacklist": "",
        "custom_script": "",
        "download_dir": "",
        "export_dir": "output",
        "force_download": false,
        "nw_compression_level": 0,
        "nw_version": "0.42.0-beta1",
        "output_pattern": "",
        "sdk_build": false,
        "uncompressed_folder": false,
        "whitelist": "",
        "windows-x64": true
    },
    "webkit": {},
    "window": {
        "icon": "png_128.png",
        "id": "titansoftime",
        "kiosk": true,
        "title": "titansoftime"
    }
}
```
![image](https://user-images.githubusercontent.com/6549763/67138237-eeffa380-f205-11e9-8141-861cf4f11a3c.png)

**Comment by jyapayne** [comment]
Hey Kevin.

It seems like your project is fine, especially since you can build it with other builders. One thing you might try is selecting a non beta version of NWJS. I tried exporting the same version as you selected and  the exported program crashed on me three times before opening. `0.41.3` seems to work flawlessly for me.

Another thing you might try is the Windows 32 bit export and see if that one works. I've heard people have some issues with specific architectures for some reason.

Other than that, I would need a copy of your specific project (I understand you may not want to do that) in order to attempt to reproduce the issue.

**Comment by titansoftime** [comment]
I found the problem. File size. I have a WebGL game with several Gigs of texture files. Look slike I'm going to have to figure something else out =[

**Comment by jyapayne** [comment]
Just an FYI, you can load files from outside the package by referencing them in your JS. See here: https://github.com/jyapayne/Web2Executable/issues/34
