### ISSUE TITLE
Allow user to see outstanding issues from GUI

### ISSUE THREAD

**Issue by JavaScriptDude** [jyapayne/Web2Executable#45]
It is difficult when there are issues in the fields in the GUI and no mention of what the outstanding issues are. In my case, I had no idea that there was an error.log file and once I found it (kind of by accident), I was able to debug the issue and get the "Export" button to show up.

It would be great to have the GUI guide the user that there are outstanding issues blocking execution. One easy solution is to keep the "Export" button enabled but block the execution if there are issues and present a message box listing the outstanding issues.

In the meantime, it may also be a good idea to mention the error.log file in your readme.md.

**Comment by jyapayne** [comment]
Thank you for the feature request. My plan for this is to have the field highlight in red when something is wrong and have a popup showing the error message. Unfortunately, the design can't accommodate for this change easily, which is why I'm redesigning the app from the ground up. My time is limited for working on issues, but I'll try to fix this for the current version if I have time.

I put a note in the readme about the error.log file, thanks for the info.

**Comment by bbyit** [comment]
I had no idea about the error log, thanks~!! Would have been real handy earlier..
On Mac OS X, or at least my Mac, only Windows will compile if you happen to move the app icon and forget. Took me awhile to piece that one together :P

**Comment by jyapayne** [comment]
Fixed in the latest commit. I'll update the build once I get a few more issues in.

**Comment by jyapayne** [comment]
Build is up!
