### ISSUE TITLE
Support for App Protocol

### ISSUE THREAD

**Issue by BenjaminDobler** [jyapayne/Web2Executable#60]
Seems like currently it`s impossible to use app protocol for the main file.
https://github.com/nwjs/nw.js/wiki/App-protocol
Setting the main html file to: "app://index.html"
Won`t let me export. Maybe just a checkbox which adds the app://?

Thanks for your great project!

**Comment by jyapayne** [comment]
Hey Ben,

The problem with doing that is that it creates an issue with exporting the executable. When specifying the app protocol, nwjs expects that your application will lay in the current directory (instead of the temporary directory that nwjs creates for the app). This results in a blank "NWJS" page. I don't think there is a way to do this (currently) without breaking how I currently have exporting set up.

What is the reason that you need the app protocol?
