### ISSUE TITLE
Apps built on the Mac don't open on Windows

### ISSUE THREAD

**Issue by Braveatom** [jyapayne/Web2Executable#64]
Title says it all really - when exporting to Windows, using the Mac app the windows apps don't open / show (not sure which) - only when they are built on Windows do they open. I'm using Windows 7.1 in Bootcamp to do the tests

**Comment by 2braincells2go** [comment]
Student of mine had same issue. But they did actually work on a real windows machine.

**Comment by Braveatom** [comment]
OK cool - I'll fire it up tomorrow and test - thanks for the tip

**Comment by jyapayne** [comment]
There's some weirdness with building apps that makes them not work too well on Windows Virtual Machines and Bootcamp. They should work fine on real machines, just like Woody says.

I'm not sure if there's anything I can do. I've looked into it, but I can't find any information. In theory, they should work since building them is the same process regardless of which platform you are on.

**Comment by Braveatom** [comment]
No biggie here as I test before sending - so easy enough to build on the test machine too - thanks
