### ISSUE TITLE
[OSX] - option for app.nw to be uncompressed folder

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#83]
Feature request maybe - at the moment the app.nw within the mac app package is compressed even if compression set to 0 under Compression Settings - for Mac apps 
I find less issues occur if the app.nw is just a folder named as app.nw (uncompressed). It is easy enough to use Unarchiver or something but would be nice to have the option in W2E for OSX packaging.
Also some unnecessary files appear along with the app.nw and nw.icns files - again they can be manually deleted but a hassle (ChromiumAATTest.ttf, missingimage.png, etc) - see attached jpg.

Cheers.

![appdross](https://cloud.githubusercontent.com/assets/11089335/10031400/e6db53e6-6174-11e5-8793-828c09a97ac7.jpg)

**Comment by jyapayne** [comment]
The app.nw itself is not really ever "compressed". What the compression refers to is the actual executable size, which is the NW.js binary itself since it is usually the size hog. The only thing I do to the app.nw is add it to a zip archive that has a compression of 0. Are there specific issues you are running into with the default behaviour of the zipped app.nw?

As for the extra files, I simply copy all of the files from the NW.js app folder. As far as I know, these files could be necessary for certain things, which is why I don't touch them.

Cheers!

**Comment by Blatman** [comment]
Not major issues but I tend to put some files in above the app.nw folder and if it is zipped rather than just a folder then I get a path error - see snap

![zipfold](https://cloud.githubusercontent.com/assets/11089335/10051697/c41ef79e-621a-11e5-8e39-c8be0ce444f5.jpg)

Also I checked the cruft files and they appear to be fragments left in the NWjs package, maybe in some cases NWjs needs them.

Cheers.

**Comment by jyapayne** [comment]
Web2Exe doesn't support that workflow, mostly because it's not possible on the other platforms. I would be happy to add that feature for OS X specific exports. However, the OS X build tool that I use seems to no longer work and is not being updated any longer (py2app). Which means that I can't update the code for OS X versions until I find a workaround.

But, if you use Windows, I can update Web2Exe for that platform.

These tools seem to not be working with me very well, and I'm constantly looking for a solution to build OS X apps from python. I've tried cx_freeze, pyinstaller and py2app, but none of them are working any more. Unfortunately, the ecosystem for building native apps from python is a bit lacklustre, and it's a difficult problem to solve.

**Comment by Blatman** [comment]
OK Joey that's fine - it would be a nice enhancement for the OSX packager (not required for Win) but not a major - the py2app stuff is probably more of an issue going forward (Ronald looks snowed under with issues).
W2E works well on Mavericks for me and I can get round the unzipping/etc issues manually. Presumably until py2app is updated I guess W2E on Yosemite/El Capitan is going to be problematic?

Cheers,
Blane

**Comment by jyapayne** [comment]
Cool, at least you have a workaround :) You are correct about Yosemite/El Capitan. It's possible that W2E could work on them, but there's no guarantee until py2app gets updated or pyinstaller starts to work properly.

Cheers!

**Comment by jyapayne** [comment]
I've finally managed to get pyinstaller to work! :) That means I can work on this feature request for you!

**Comment by jyapayne** [comment]
See the new [downloads page](https://github.com/jyapayne/Web2Executable/wiki/Downloads) for version 0.2.7b, which has an option in the compression tab just for you :)

**Comment by Blatman** [comment]
Superb - the file for 10.10 works fine on both 10.9.5 and 10.10.5

Note: tried the file for 10.7+ (-leg) and failed to start on both (2 icons flash up in dock as per usual but neither persist and get 255 error in Console logs).

Cheers.

**Comment by jyapayne** [comment]
Yeah, there's some issue with running the 10.7 build on newer Mac OSX versions. That's why I included the 10.10 version. I assume this addresses your feature request, so I'm closing the issue.
