### ISSUE TITLE
Will you ever make a similar tool for Electron?

### ISSUE THREAD

**Issue by sapioit** [jyapayne/Web2Executable#96]
^
Just curious... it would be a great addition to your apps list...

**Comment by jyapayne** [comment]
Funny you should mention that :) I have been considering either making a separate tool for Electron, or add a "back-end" selection mechanism to Web2Exe where you could choose Electron instead of NW.js. 

I just didn't know how interested people would be in this piece of functionality/this separate application, so I was holding off on it. 

Some of the benefits of Electron vs NW.js for Web2Exe are:

- Custom plugins written in Node.js
- More control over exported application
- External files and folders
- Supported by Github :)

**Comment by Inateno** [comment]
Funny I'm also looking at Electron since a while but not using it 'cause love Web2Exe :)

If as you mentionned @jyapayne there is these "plus" and nothing less, then for me we should use it.
I also saw on Twitter a guys talking about Electron because it include WebGL2.

Why not change if it's better ? Ofc if we can just choose which one to use with a combo it's better!

**Comment by jyapayne** [comment]
@Inateno, There are a couple of downsides. One is that jQuery will have to be loaded within the main.js file. See [here](https://github.com/atom/electron/issues/254). This would also mean that any script that detects itself being the in the CommonJS framework would also need to be included this way. It's not a super big deal, and it can be worked around if no node.js functionality is needed.

Another downside is that it is a bit more difficult to integrate into Web2Exe, since Web2Exe was written with NW.js in mind. It would require quite a bit of re-factoring, but it's not impossible. I would likely need a separate UI selection specifically for Electron, since it has the ability to have finer grain control.

Other than those two things, there isn't really too much of a concern. If it's something you guys want, it's definitely on the table :)

**Comment by Inateno** [comment]
Yeah I see what you mean about "amd ready frameworks".
But that's normal since you are in a "NodeJS environment", the fact is that NW.js create a window scope which is nice but not "normal" (if I'm right).

But not a problem for me I'm using RequireJS on the whole project ^^

**Comment by sapioit** [comment]
OR you could have Web2Exe stop and continue it as a fork called Web2Exe-NWJS and have a new one (maybe forked from this one) Web2Exe-Electron (for clarity in names)...

**Comment by jyapayne** [comment]
@sapioit That's also another possible outcome :) I'll have a think about what is the best option and try some things out.

**Comment by sapioit** [comment]
Either way, I am going to make some sample apps for/with Electron, whenever that tool is ready... for nwjs I have a [pull request for a fix for a sample app](https://github.com/zcbenz/nw-sample-apps/pull/36) and I am planing to make my own [https://github.com/Sapioit-com/nwjs-example-apps](example apps)...

**Comment by sapioit** [comment]
However, what I'd like to see is an alternative with PHP instead of node.js ...

**Comment by 2braincells2go** [comment]
My two cents and might only be worth one:)

Please do not stop or retire current Web2Exe in favor of Electron. Not saying Electron is not worthy of including, but current Web2Exe is a work horse.

I say build it into Web2Exe as an option if possible so you do not have two separate software to maintain.

Cheers!

**Comment by sapioit** [comment]
^ I totally agree with not giving up on nw.js in the favour of electron. However, I think a different app is required for Electron, since they work fundameltally different, when talking about compiling into executables.

**Comment by jyapayne** [comment]
@2braincells2go I would never retire Web2Exe :) If I do go the route of a separate application, both would be updated.

@sapioit You are correct in saying that packaging Electron apps is a completely different process. However, building a completely different application would certainly take much more time than building on functionality to Web2Exe.

**Comment by sapioit** [comment]
Any way it would be, I am already looking into developing for electron, and cannot figure out how to get the binaries... by the time the tool would be done, I'll use it for sure, to make the binaries deployment easier... oh, and to not get the smallest app have 100+ MB...

**Comment by sapioit** [comment]
By the way, any idea how to build executables/binaries on Windows (not FOR Windows, but UNDER Windows)? I figured out up to having a .asar tar archive with the content and dragging it into the electron window, but no further... and there is no such video on youtube or article anywhere on the internet where I've looked for...

**Comment by jyapayne** [comment]
@sapioit You have to place the .asar archive in the resources folder, right by the atom.asar file. Alternatively, you can put your package.json, main.js and index.html files in the `resources\default_app` directory and then run electron.exe.

**Comment by sapioit** [comment]
wait... but isn't the .asar the archive containing the package.json, main.js and whatever else (I mean just the content of my working directory, archived)? Why must I copy everything again there?

**Comment by sapioit** [comment]
Damn, why isn't there any tutorial online? I will make a video tutorial and put it on youtube, once I get the hang of it. 

Also, someone said that a Electron app can be packed to up to a few MB, as opposed to 100+MB from nw.js ...

**Comment by jyapayne** [comment]
I said alternatively :) You can either copy all your files to the resources/default_app folder OR pack it into an asar file and put it in the resources folder. 

I doubt that the electron app can be packed into a few MB. The NW.js files are equivalent in size to the Electron binaries, so I don't think it would be possible.

**Comment by sapioit** [comment]
Apparently, I skipped the "alternatively" word... thanks!
I think I will try to make my own version of web2executable, but for electron... I think I will name it "Colider"... and have it written in Electron...
I'd making it with python, but I do not know how to have it cross-OS or how to make interfaces in python... as a programmer, I know it's not "that difficult" and can be learned quite easily, with tutorials from youtube, but I do not want to spend a lot of time making it... and, after all, it does not have to be compuled... I can have it delivered as source, tar-ed in .asar, or as a Electronapp packed into binnaries...

Also, I found [electron-packer](https://github.com/maxogden/electron-packager), which I have no idea how to get running at all, so it might not be included in the first releases... if I will ever get a working product...

**Comment by jyapayne** [comment]
Alright, that's always an option :) Collider is a cool name. I wish you good luck! If you want any ideas or feedback, you can always email me :)

I thought when I started Web2Exe that I would only spend a month on it. But here I am a year and a half later :P

**Comment by sapioit** [comment]
Only one: how did you solved the problem with making the binaries? I mean, how did you got the list of links required to downloading the binaries for each version? I mean, I could try to crawl the Releases page and look for the download links, or are you manually adding the versions and download links into a file, which is used by your software to download the binaries?

**Comment by jyapayne** [comment]
I look at the [changelog](https://raw.githubusercontent.com/nwjs/nw.js/master/CHANGELOG.md) file and parse out the versions and reconstruct the URL based on those versions.

To do the same with electron, you'd have to parse the releases page or find a similar document.

**Comment by sapioit** [comment]
Thanks!

**Comment by sapioit** [comment]
Ok, I think I got that setteld... but got into another problem... How did you managed to change the icon for the executables? What library have you used, or what method?

**Comment by jyapayne** [comment]
That was not an easy problem. Basically, I wrote my own executable parser in Python in order to find where the icon is and replace it. I had to also use Pillow to convert the png or jpeg files to ico files in order to replace them correctly. 

It's a difficult problem to solve in nodejs, since there isn't any equivalent image library to Pillow. If you're interested in the exe reading source code, it's in my repo [PePy](https://github.com/jyapayne/PePy)

**Comment by jyapayne** [comment]
The code in that repo is a little messy, since I threw it together quite quickly, but if you have questions, I'd be happy to answer!

**Comment by sapioit** [comment]
I just found another answer, but for Node... since I'm trying to make my app in Node...  [First](http://stackoverflow.com/questions/21304845/changing-node-webkit-app-icon-on-windows-from-cli) and [Second](http://stackoverflow.com/questions/26986874/how-do-i-programmatically-change-icon-of-a-windows-executable-and-mac-applicatio).

I don't know which one works, or if any, but I will try them when I get the time to... Thanks for the help!

**Comment by jyapayne** [comment]
Either of those solutions are fine if you want to build the application for windows only. But they won't work if you'd like to create a windows app from within Mac

**Comment by sapioit** [comment]
No? Well, I might need to add an exception for Mac, than... thanks for pointing that out for me! Also, aren't they also possible on Linux, if Wine and dotNet2.0 are installed? That's what I thought, when I read about them...

**Comment by jyapayne** [comment]
That is true, but most people don't like to install Wine, I found. But it should be a reasonable solution to use Wine :)

**Comment by sapioit** [comment]
Well, I'd like to find something that works cross-platform... but it looks like I can't find anything cross-platform for node...

**Comment by jyapayne** [comment]
@sapioit If you are still looking to use Electron, I recently converted Web2Exe to [Electrify](https://github.com/jyapayne/Electrify), which exports using Electron.

**Comment by sapioit** [comment]
Thanks! I'll start using it!

**Comment by 2braincells2go** [comment]
you never cease to amaze me Joey! i have got to try this baby out:) hope my limited brain power can grasp, lol.

**Comment by sapioit** [comment]
...I think I broke something...
---------------------------
Error!
---------------------------
Traceback (most recent call last):
  File "command_line.py", line 419, in download_file_with_error_handling
  File "<string>", line 751, in download_file
  File "command_line.py", line 1108, in get_redirected_url
  File "urllib\request.py", line 469, in open
  File "urllib\request.py", line 579, in http_response
  File "urllib\request.py", line 507, in error
  File "urllib\request.py", line 441, in _call_chain
  File "urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

---------------------------
OK   
---------------------------

**Comment by jyapayne** [comment]
@sapioit Right now, in order to have all of the window options available, I generate a main.js file based on your selections. So when you specify a index.html file, the generated main.js uses it for the main BrowserWindow instance. You can specify JS that gets injected using Inject JS Start and Inject JS End. If you have ideas on how to make this more friendly, it would help a lot :) 

As for your error, which version of Electron did you select to download? Right now, there are now 32 bit versions of Mac (I forgot to remove that option).

**Comment by jyapayne** [comment]
Woody, let me know how it goes :) It's still a little rough around the edges, so feedback is always welcome :)

**Comment by 2braincells2go** [comment]
you bet ya Joey. looks pretty good. opened an issue (at git/electrify) and attempted to push change but my git is not getting:) think the download for electron in our cfg file not good. changed it as shown in issue and now working for me.

**Comment by sapioit** [comment]
> Right now, you can't export to 32 bit Mac (I forgot to remove that option, since electron.js has no 32bit download).
Probably why I've got the error.

**Comment by jonmulcahy** [comment]
fantastic stuff @jyapayne
